version: '3.8'

services:
  # Serviço MongoDB
  mongodb:
    container_name: mongodb_hvac_loader
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "${MONGODB_VOLUME_DIR:-./data/mongodb}:/data/db"
      - ./scripts/mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hvacuser
      - MONGO_INITDB_ROOT_PASSWORD=hvacpass
      - MONGO_INITDB_DATABASE=hvac_db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
