version: '3.8'

services:
  # Serviço LocalStack para simular AWS S3 
  localstack:
    container_name: localstack_hvac_loader
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"           
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=s3        
      - DEFAULT_REGION=us-east-1     
      - AWS_ACCESS_KEY_ID=test       
      - AWS_SECRET_ACCESS_KEY=test   
      - DOCKER_HOST=unix:///var/run/docker.sock 
      - DEBUG=1                       
      - DATA_DIR=/tmp/localstack/data 
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack" 
      - "/var/run/docker.sock:/var/run/docker.sock"                   
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hvac_loader_net

  # Serviço MongoDB
  mongodb:
    container_name: mongodb_hvac_loader
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "${MONGODB_VOLUME_DIR:-./data/mongodb}:/data/db"
      - ./scripts/mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hvacuser
      - MONGO_INITDB_ROOT_PASSWORD=hvacpass
      - MONGO_INITDB_DATABASE=hvac_db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hvac_loader_net

  # Inicializar recursos do LocalStack
  localstack-init:
    container_name: localstack_initializer
    image: amazon/aws-cli:latest
    command: bash /app/init-localstack.sh
    volumes:
      - ./scripts:/app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - hvac_loader_net
    restart: "no" 

networks:
  hvac_loader_net:
    driver: bridge